export const Data=[
    
    {id:0,name:"iQOO 12 5G", price:57999,img:"./mobile/iQOO 12 5G.jpg",imgs:["./mobile/iQOO 12 5G.jpg","./mobile/iqoo.jpg","./mobile/iqoo(1).jpg","./mobile/iqoo(2).jpg","./mobile/iqoo(3).jpg"],heading1:"16GB",heading2:"512GB" ,ditile:"50MB",ditiles:"50MB + 64MB", brands:"iQOO",item:"Mobiles", amount: 1},
    {id:1,name:"Redmi Note 13 5G ", price:21999,img:"./mobile/Redmi Note 13 5G.jpg",imgs:["./mobile/Redmi Note 13 5G.jpg","./mobile/redmi c (1).jpg","./mobile/redmi c (2).jpg","./mobile/redmi c (3).jpg","./mobile/redmi c (4).jpg","./mobile/redmi c (5).jpg"],heading1:"12GB",heading2:"256GB" ,ditile:"50MB",ditiles:"108MB + 40MB + 8MB", brands:"Redmi",item:"Mobiles", amount: 1},
    {id:2,name:"Redmi 13C 5G ", price:11999,img:"./mobile/Redmi 13C 5G.jpg",imgs:["./mobile/redmi (1).jpg","./mobile/redmi (4).jpg","./mobile/redmi (2).jpg","./mobile/redmi (3).jpg","./mobile/redmi (5).jpg","./mobile/redmi (6).jpg"],heading1:"6GB",heading2:"128GB" ,ditile:"14MB",ditiles:"50MB + 28MB", brands:"Redmi",item:"Mobiles" , amount: 1},
    {id:3,name:"Oppo", price:7699,img:"./mobile/oppo.jpg",imgs:["./mobile/oppo.jpg","./mobile/oppo(1).jpg","./mobile/oppo(4).jpg","./mobile/oppo(2).jpg","./mobile/oppo(3).jpg","./mobile/oppo(5).jpg","./mobile/oppo(6).jpg"],heading1:"4GB",heading2:"128GB" ,ditile:"28MB",ditiles:"50MB + 5MB", brands:"Oppo",item:"Mobiles", amount: 1},
    {id:4,name:"Dell ", price:35890,img:"./mobile/del (1).webp",imgs:["./mobile/del (1).webp","./mobile/del (2).webp","./mobile/del (3).webp","./mobile/del (4).webp","./mobile/del (5).webp"],heading1:"16GB",heading2:"512GB" ,ditile:"Intel Core i3 12th Gen 1215U",ditiles:"Windows 11 Home   (15.6 Inch, Platinum Silver, 1.65 Kg, With MS Office)", brands:"Del",item:"Leptop" , amount: 1},
    {id:5,name:"HP  ", price:35890,img:"./mobile/hp (1).webp",imgs:["./mobile/hp (1).webp","./mobile/hp (4).webp","./mobile/hp (2).webp","./mobile/hp (3).webp","./mobile/hp (5).webp","./mobile/hp (6).webp","./mobile/hp (7).webp","./mobile/hp (8).webp","./mobile/hp (9).webp","./mobile/hp (10).webp"],heading1:"8GB",heading2:"512GB" ,ditile:"Intel Core i5 12th Gen 1235U",ditiles:"Windows 11 Home   (15.6 Natural Silver, 1.65 Kg)", brands:"HP",item:"Leptop" , amount: 1},
    {id:6,name:"Infinix INBook", price:25990,img:"./mobile/infinix (1).webp",imgs:["./mobile/infinix (1).webp","./mobile/infinix (4).webp","./mobile/infinix (2).webp","./mobile/infinix (3).webp","./mobile/infinix (5).webp","./mobile/infinix (6).webp","./mobile/infinix (7).webp","./mobile/infinix (8).webp","./mobile/infinix (9).webp","./mobile/infinix (10).webp","./mobile/infinix (11).webp","./mobile/infinix (12).webp","./mobile/infinix (13).webp","./mobile/infinix (14).webp"],heading1:"8GB",heading2:"256GB" ,ditile:"Intel Core i3 11th Gen 1115G4",ditiles:"Windows 11 Home    (15.6 Inch, Blue, 1.58 Kg)", brands:"Infinix",item:"Leptop" , amount: 1},
    {id:7,name:"Lenovo IdeaPad Slim 3", price:59390,img:"./mobile/lenova (1).webp",imgs:["./mobile/infinix (1).webp","./mobile/infinix (4).webp","./mobile/lenova  (2).webp","./mobile/lenova  (3).webp","./mobile/lenova (5).webp","./mobile/lenova (6).webp","./mobile/lenova (7).webp","./mobile/lenova (8).webp","./mobile/lenova (9).webp"],heading1:"16GB",heading2:"512GB" ,ditile:"Intel Core i5 13th Gen 13420H",ditiles:"Windows 11 Home    (15.6 Inch, Arctic Grey, 1.62 Kg With MS Office)", brands:"lenovo",item:"Leptop" , amount: 1}
    ]